// @ts-nocheck

// This file is generated by tauri-specta from plugins/db/src/lib.rs.

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";

type Result<T, E> = { status: "ok"; data: T } | { status: "error"; error: E };

function command<T>(
  name: string,
  args?: Record<string, unknown>,
): Promise<Result<T, string>> {
  return TAURI_INVOKE<T>(`plugin:db|${name}`, args)
    .then((data) => ({ status: "ok", data }))
    .catch((error) => {
      if (error instanceof Error) throw error;
      return { status: "error", error: error as string };
    });
}

export const commands = {
  listMeetings: (input: ListMeetingsInput) =>
    command<MeetingPage>("list_meetings", { input }),
  getMeeting: (input: GetMeetingInput) =>
    command<Meeting>("get_meeting", { input }),
  getMeetingTranscript: (input: GetMeetingTranscriptInput) =>
    command<TranscriptPage>("get_meeting_transcript", { input }),
  getRecurringMeetingHistory: (input: GetRecurringMeetingHistoryInput) =>
    command<MeetingPage>("get_recurring_meeting_history", { input }),
  execute: (sql: string, params: JsonValue[]) =>
    command<JsonValue[]>("execute", { sql, params }),
  executeTransaction: (statements: TransactionStatement[]) =>
    command<number[]>("execute_transaction", { statements }),
  executeProxy: (sql: string, params: JsonValue[], method: string) =>
    command<ExecuteProxyResult>("execute_proxy", { sql, params, method }),
  getLegacyImportReport: () =>
    command<LegacyImportReport>("get_legacy_import_report"),
  getLegacyCleanupStatus: () =>
    command<LegacyCleanupStatus>("get_legacy_cleanup_status"),
  cleanupLegacyFiles: () =>
    command<LegacyCleanupResult>("cleanup_legacy_files"),
  runLegacyImport: (dryRun: boolean) =>
    command<string>("run_legacy_import", { dryRun }),
  subscribe: (
    sql: string,
    params: JsonValue[],
    onEvent: TAURI_CHANNEL<QueryEvent>,
  ) => command<SubscriptionRegistration>("subscribe", { sql, params, onEvent }),
  unsubscribe: (subscriptionId: string) =>
    command<null>("unsubscribe", { subscriptionId }),
  getStartupStatus: (): Promise<StartupStatus> =>
    TAURI_INVOKE("plugin:db|get_startup_status"),
  waitUntilReady: () => command<null>("wait_until_ready"),
};

export type ActionItem = {
  id: string;
  assignee_human_id: string;
  status: string;
  text: string;
  due_at: string;
  completed_at: string | null;
};
export type DependencyAnalysis =
  | { kind: "reactive"; data: { targets: DependencyTarget[] } }
  | { kind: "non_reactive"; data: { reason: string } };
export type DependencyTarget =
  | { kind: "table"; data: string }
  | { kind: "virtual_table"; data: string };
export type Document = {
  id: string;
  kind: string;
  template_id: string;
  title: string;
  markdown: string;
  sort_order: number;
  created_at: string;
  updated_at: string;
};
export type ExecuteProxyResult = { rows: JsonValue[] };
export type GetMeetingInput = { meeting_id: string };
export type GetMeetingTranscriptInput = {
  meeting_id: string;
  offset: number | null;
  limit: number | null;
};
export type GetRecurringMeetingHistoryInput = {
  meeting_id: string;
  limit: number | null;
  offset: number | null;
};
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | Partial<{ [key in string]: JsonValue }>;
export type LegacyCleanupResult = {
  deletedFileCount: number;
  deletedBytes: number;
};
export type LegacyCleanupStatus = {
  migrationReady: boolean;
  migrationVerified: boolean;
  available: boolean;
  alreadyCleaned: boolean;
  fileCount: number;
  totalBytes: number;
  sourceRoot: string;
  blockingReason: string | null;
};
export type LegacyImportItemReport = {
  sourcePath: string;
  sourceKind: string;
  sourceSha256: string;
  status: string;
  discoveredCount: number;
  importedCount: number;
  matchedCount: number;
  skippedCount: number;
  conflictCount: number;
  error: string;
};
export type LegacyImportReport = {
  state: StorageMigrationState;
  latestRun: LegacyImportRun | null;
  items: LegacyImportItemReport[];
  targets: LegacyImportTargetReport[];
};
export type LegacyImportRun = {
  id: string;
  importerVersion: number;
  sourceRoot: string;
  dryRun: boolean;
  status: string;
  discoveredCount: number;
  importedCount: number;
  matchedCount: number;
  skippedCount: number;
  conflictCount: number;
  errorCount: number;
  startedAt: string;
  completedAt: string | null;
  error: string;
};
export type LegacyImportTargetReport = {
  sourcePath: string;
  tableName: string;
  targetId: string;
  status: string;
  error: string;
};
export type ListMeetingsInput = {
  query: string | null;
  series_id: string | null;
  limit: number | null;
  offset: number | null;
};
export type Meeting = {
  id: string;
  title: string;
  kind: string;
  status: string;
  created_at: string;
  updated_at: string;
  started_at: string;
  ended_at: string;
  timezone: string;
  language: string;
  series_id: string;
  note: Document | null;
  summaries: Document[];
  participants: Participant[];
  action_items: ActionItem[];
};
export type MeetingListItem = {
  id: string;
  title: string;
  kind: string;
  status: string;
  created_at: string;
  updated_at: string;
  started_at: string;
  ended_at: string;
  timezone: string;
  language: string;
  series_id: string;
};
export type MeetingPage = {
  meetings: MeetingListItem[];
  pagination: Pagination;
};
export type Pagination = {
  offset: number;
  limit: number;
  returned: number;
  total: number | null;
  next_offset: number | null;
};
export type Participant = {
  human_id: string;
  display_name: string;
  email: string;
  role: string;
  job_title: string;
  organization_id: string;
  organization_name: string;
};
export type QueryEvent =
  | { event: "result"; data: JsonValue[] }
  | { event: "error"; data: string };
export type StartupPhase =
  | "preparing_database"
  | "migrating_database"
  | "importing_legacy_data"
  | "ready"
  | "failed";
export type StartupStatus = {
  phase: StartupPhase;
  migrationCurrent: number | null;
  migrationTotal: number | null;
};
export type StorageMigrationState = {
  phase: string;
  latestRunId: string;
  parityVerified: boolean;
  cutoverAt: string | null;
  rollbackUntil: string | null;
  lastError: string;
  updatedAt: string;
};
export type SubscriptionRegistration = {
  id: string;
  analysis: DependencyAnalysis;
};
export type TAURI_CHANNEL<TSend> = null;
export type TransactionStatement = {
  sql: string;
  params: JsonValue[];
  expectedRowsAffected?: number | null;
};
export type TranscriptPage = {
  meeting_id: string;
  text: string;
  words: JsonValue[];
  pagination: Pagination;
};
